<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.0.0.1</Version>

        <Author>FabioFrog91</Author>
        <Name>FROG</Name>
        <Punchline>Fetch Retainer Only Goods</Punchline>
        <Description>FROG è un plugin Dalamud per Final Fantasy XIV progettato per indicizzare, organizzare e pianificare il recupero degli oggetti tra inventari, retainers, personaggi e Free Company Chest.</Description>
        <RepoUrl>https://github.com/FabioFrog91/FROG</RepoUrl>
        <Tags>FFXIV;Dalamud;Inventory</Tags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\CriticalCommonLib\CriticalCommonLib.csproj" />
    </ItemGroup>
</Project>